algo = input('digite algo ')
print('o tipo primitivo desse valor é ', type(algo))
print(algo.isalnum())
print('é alfabeto?', algo.isalpha())
print(algo.isascii())
print(algo.isdigit())
print(algo.isalnum())
print(algo.islower())
print(algo.isdecimal())
print(algo.isidentifier())
print(algo.isnumeric())
print(algo.isprintable())
print(algo.isspace())
print(algo.istitle())
print(algo.isupper())